apiVersion: v1 
kind: Service 
metadata: 
  name: deployment-srv 
spec:
  type: NodePort #ladbalancer #clusterip
  selector:
    app: myapp
  ports:
    - name: http 
      port: 80 
      targetPort: 80